pool: kpool
trigger: none
variables:
  workdir: 'C:\Devops\Witagnet\vsts-agent-win-x64-4.259.0\_work\8\s'
  azbaarm:  'newfedcon'
steps:


- task: PowerShell@2
  displayName: 'Powershell task'
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World"'

#- task: PowerShell@2
#  displayName: 'Azurelogin'
#  inputs:
#    targetType: 'inline'
#    script: 'az login'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workdir)'
    backendServiceArm: '$(azbaarm)'
    backendAzureRmResourceGroupName: 'reg1'
    backendAzureRmStorageAccountName: 'stornew420'
    backendAzureRmContainerName: 'newcont'
    backendAzureRmKey: 'def.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(workdir)'
    environmentServiceNameAzureRM: '$(azbaarm)'

#- task: TerraformTask@5
#  displayName: 'Terraform Apply'
#  inputs:
#    provider: 'azurerm'
#    command: 'apply'
#    workingDirectory: '$(workdir)'
#    commandOptions: '-auto-approve'
#    environmentServiceNameAzureRM: '$(azbaarm)'

    


